### ISSUE TITLE
Word Count Pop-Up when on Auto compile every second the document updates

### ISSUE THREAD

**Issue by mahyarrs** [fjwillemsen/NativeOverleaf#10]
I get this annoying message constantly. I'm on windows 10 (64-bit) and using the latest version of the app.
![bug](https://user-images.githubusercontent.com/29644181/195239439-d1ac2818-463a-4114-9d9b-425479624bbf.png)

**Comment by fjwillemsen** [comment]
That is correct, it is designed to do this to track the wordcount. You can disable wordcount tracking in the native overleaf menu (see image), or if you want to keep wordcount tracking enabled, I can look into adding a cooldown period. 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/6725103/197558160-67f58157-59cb-421e-a01c-eba0189b2736.png">
