### ISSUE TITLE
M1 Mac - SourceEditor and LeftSidebarMenu Not Darkmode (Bug)

### ISSUE THREAD

**Issue by TheMathGuyd** [fjwillemsen/NativeOverleaf#14]
I prefer the darkmode that is already present on the web's source editor. This download version unfortunately has messed up the background, so the white text is practically invisible.
<img width="1440" alt="Screenshot 2023-01-26 at 9 21 20 AM" src="https://user-images.githubusercontent.com/85257386/214890965-651dcc6b-4587-404f-a0fe-59993870f50d.png">
Similar text invisibility in the left sidebar menu, when it is summoned. 
<img width="394" alt="Screenshot 2023-01-26 at 9 24 15 AM" src="https://user-images.githubusercontent.com/85257386/214891120-4e898682-db9d-4432-b4b6-d3b7a137698b.png">

**Comment by fjwillemsen** [comment]
Hi, thank you for mentioning this. What are the steps to reproduce this issue?

**Comment by fjwillemsen** [comment]
Partially fixed (for the sidebar) in [version 1.8.0](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.8.0).

**Comment by fjwillemsen** [comment]
@TheMathGuyd could you let me know what platform and architecture you're on and what the steps are to reproduce this issue?

**Comment by kenzaelkouhen** [comment]
@fjwillemsen I just downloaded the native overleaf app on my mac intel x64, and I have the same issue, not being able to see the source code correctly because it is too white as in the image attached by. Hope it is gonna be fixed, thank you!

**Comment by nanbaima** [comment]
For me, MacOS M1 Pro, this problem still happens, but only on the references imported via Zotero/Mendeley:

<img width="1027" alt="image" src="https://github.com/fjwillemsen/NativeOverleaf/assets/19144999/0ea28bab-fc65-45c2-98e8-60730496cdf0">

Should I create a new issue?

**Comment by nanbaima** [comment]
This issue also happens in the share project view.
Even in version 1.9.0

**Comment by fjwillemsen** [comment]
I completely agree that it is very annoying, but so far I am unable to reproduce - for me it is as expected in the screenshot below. So far I think it may have to do with outdated or inconsistent LocalStorage, but if I'm unable to reproduce this issue I can't fix it. Does it always happen when switching to dark mode, or only under specific circumstances? 
<img width="348" alt="image" src="https://github.com/fjwillemsen/NativeOverleaf/assets/6725103/0d679dac-c145-40c5-8d08-2c31fd1ce852">

**Comment by fjwillemsen** [comment]
As there has been no response, I will close the issue for now. Feel free to reopen if you can provide me a way for to reproduce the issue, or submit a pull request to fix it.
