### ISSUE TITLE
Option for custom fonts?

### ISSUE THREAD

**Issue by taprobane99** [fjwillemsen/NativeOverleaf#15]
in the website version I can easily replace the editor font using a browser extension like Stylus and:

@font-face {
    font-family: "Menlo";
    src: local("Cascadia Code");
}

can we have something similar here?

**Comment by fjwillemsen** [comment]
Implemented in [version 1.8.0](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.8.0). Feel free to reopen if you have any feedback!

**Comment by taprobane99** [comment]
great. thanks!
