### ISSUE TITLE
Download PDF button has no response

### ISSUE THREAD

**Issue by tommy307507** [fjwillemsen/NativeOverleaf#17]
Both the download button in the pdf viewer and in the menu does nothing,
Clicking the one in the menu opens an empty pop up.
The icon in my taskbar is responsive when I click download but no message box or pop up.

I downloaded the windowsx86 version on github. 

![image](https://user-images.githubusercontent.com/49487505/224232746-94af1b0a-0c33-4e27-9a2d-94ac0e2b8d6b.png)

**Comment by rafisics** [comment]
I am having the same trouble.

**Comment by fjwillemsen** [comment]
Thank you for letting me know! I have not modified the download buttons, so this is an interesting bug. I am unable to reproduce this issue on macOS, so I will test on Windows shortly.

**Comment by fjwillemsen** [comment]
For me during testing, it worked as expected: both the buttons resulted in the PDF file showing up in the Downloads folder. Indeed the button in the sidebar causes a new, empty window to open, which I'll need to look in further. What may be confusing is that there is no confirmation of a download happening, but that is Overleaf's default behaviour. I may add this in the future, but for now, the PDF downloads fine for me. If you are unable to download the PDF, please reopen this issue with steps to reproduce.
