### ISSUE TITLE
Running locally off-line

### ISSUE THREAD

**Issue by nanbaima** [fjwillemsen/NativeOverleaf#23]
Hello there!
I'd like to express my appreciation for the great implementation of this beneficial platform.
It's definitely something that was needed, and I've already shared it with all my colleagues in the laboratory - they loved it too! 

I have a question for you about a possible future feature.
Is it feasible to have both a local and offline instance running simultaneously, with the option to integrate with different platforms to support system versioning and conflict management (such as git)?
I understand this may be a challenging and complex request, but I'd like to start a discussion on how we can take this platform to the next level.

**Comment by fjwillemsen** [comment]
Hi, thank you so much for your loving words! While I agree that would be awesome and have thought about it myself, this app is mostly a wrapper around Overleaf and as such completely depends on Overleaf to do the compilation stage on their servers. Complex features like offline / local and git support can not be added in the same way I have added the other features: they are more like extensions while this would fundamentally change several things. As such, it would require a new application built from the ground up. While I have not used it myself, Overleaf does offer Toolkit to run an Overleaf server yourself if you're interested in that: https://github.com/overleaf/toolkit. Nevertheless, thank you for your suggestions!

**Comment by nanbaima** [comment]
Hey, thank you for getting back to me.
I understand the limitations and complexities of adding features, which would require a significant redesign and a new application built from scratch.
Once again, thank you for your work. It simplifies a lot.
