### ISSUE TITLE
Wordcount tracker down?

### ISSUE THREAD

**Issue by carlacodes** [fjwillemsen/NativeOverleaf#29]
Hi, is the wordcount tracker down? I loaded the M1/M2 version yesterday and noticed the word count tracker disappeared.

**Comment by fjwillemsen** [comment]
Hi Carla, glad to hear you are using the word count tracking! The word count tracker (and all of Native Overleaf for that matter) runs locally on your machine, so there is no external server or service that can be down in that regard, except Overleaf itself obviously. It is possible that the word count storage is corrupted or has been incorrectly loaded for some other reason. You could try disabling and re-enabling the word count tracking (the toggle with "tracking" next to it), this should trigger a re-initialization of the word count tracking. If that doesn't work, try restarting the app and repeating the disabling and re-enabling. Hope this solves your issue, please let me know!

**Comment by fjwillemsen** [comment]
@carlacodes was your problem solved this way?

**Comment by carlacodes** [comment]
Hi @fjwillemsen, sorry for the delayed reply, yes, it was solved this way, thank you! Closing this thread.

**Comment by fjwillemsen** [comment]
No problem, enjoy using Native Overleaf!
