### ISSUE TITLE
Keep state of folds and panes

### ISSUE THREAD

**Issue by RhvdG** [fjwillemsen/NativeOverleaf#31]
Perhaps this is not doable, technically, but it would be wonderful if the state of folds (manually set using ``{ % ... % }`` were preserved when closing and reopening documents; same for the panes (file tree, code, comments, PDF).

**Comment by fjwillemsen** [comment]
Hi @RhvdG, thank you for your suggestion! While this would indeed be nice, it really pertains to the inner workings of Overleaf itself, so I think your question would be better suited to try and get Overleaf to do this [via the following page](https://www.overleaf.com/learn/how-to/What_if_I_have_an_idea_for_functionality_to_improve_Overleaf%3F).
