### ISSUE TITLE
New version not codesigned on M1

### ISSUE THREAD

**Issue by taprobane99** [fjwillemsen/NativeOverleaf#35]

**Comment by fjwillemsen** [comment]
Thank you for reporting this, you were right, the self-signed certificate had expired. This has been fixed in the just-released [1.9.2](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.9.2).

**Comment by fjwillemsen** [comment]
Thank you for reporting this, you were right, the self-signed certificate had expired. This has been fixed in the just-released [1.9.2](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.9.2).
