### ISSUE TITLE
Old build detected

### ISSUE THREAD

**Issue by Photen** [fjwillemsen/NativeOverleaf#40]
This app was built a long time ago, Nativefier uses the Chrome browser (throughElectron), and it is insecure to keep using an old version of it, Please upgradeNativefier and rebuild this app.

**Comment by Brain-Eating-Amoeba** [comment]
I have the same issue

**Comment by fjwillemsen** [comment]
I've just released a security update (see https://github.com/fjwillemsen/NativeOverleaf/releases) that prevents this error in the future.
